### ISSUE TITLE
Optifine Cape is not shown

### ISSUE THREAD

**Issue by Zijuna** [TheIllusiveC4/Caelus#7] opened 2020-06-11 20:19 UTC
<!--

Caelus: 1.15.2-20-beta2
Forge: 31.2.0
Optifine: 1.15.2 U_G1_pre22
(On Linux)

The Optifine Cape is invisible, though the texture renders properly when Elytra is equipped.

The Optifine Cape should be visible at all times.

The bug should show as soon as you install both caelus and optifine and activate the cape.

Theres no real crash report but I can attach the regular game log, if that might help?

**Comment by Krystian20857** [comment] 2020-06-11 20:29
Hello Zijuna!
I was able to solve this issue now I am waiting for the branch to be merged. You can clone Caelus fork from my account and compile it by yourself.

**Comment by TheIllusiveC4** [comment] 2020-06-11 21:23
Duplicate of https://github.com/TheIllusiveC4/Caelus/issues/5

**Closed by TheIllusiveC4** 2020-06-11 21:24 UTC
Labels: bug, duplicate

**Comment by Zijuna** [comment] 2020-06-12 13:48
Not exactly a duplicate. In #5 its shown that the cape renders alongside the elytra. In my case it doesnt. Cape is invisible though the cape texture renders properly on the elytra.

**Comment by Zijuna** [comment] 2020-06-12 14:03
Im sorry, I goofed. It's not exactly a duplicate because the cape is never seen, not even with an elytra on. Though its been fixed in beta3, so thanks!
