### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by BuilderDan** [TheIllusiveC4/Caelus#2] opened 2019-07-15 04:10 UTC
#### Versions (Be specific, do not write "latest"):
* Caelus: caelus-FORGE-1.14.3-0.9.jar
* Forge: forge-27.0.16
#### Steps to Reproduce:
1. Crashed randomly. Only entities in my area that I knew of was the wandering trader and its llamas
2. For it not to crash randomly.
3. Not 100% sure, seems like just playing it might randomly occur. Sorry, I know this is very unhelpful. (Appears it was a bat)
...

Crash Log: https://pastebin.com/cDrLTt8r

**Comment by TheIllusiveC4** [comment] 2019-07-15 09:11
Is there a reason that you suspect this is a Caelus issue? Can you reproduce this with just Caelus installed? As far as I can tell, it's not called in the stacktrace. It seems like the crash was due to a bat trying to drop a null item on death and Caelus doesn't touch any of that logic. I'll need some more evidence that this is an issue on my end before proceeding further.

You could also try to update Forge, the latest version is 27.0.51, and see if that resolves your issue.

**Comment by BuilderDan** [comment] 2019-07-15 20:49
I'll keep an eye on it if it persists then I will do solo testing with just Cealus.

**Comment by TheIllusiveC4** [comment] 2019-09-07 06:41
Closing this as it has been a while without an update. If this is still an issue, and there's more information to provide, then I'll be happy to re-open it.

**Closed by TheIllusiveC4** 2019-09-07 06:41 UTC
Labels: bug
